### ISSUE TITLE
Password must be changed after ...

### ISSUE THREAD

**Issue by mar1u5** [nextcloud/password_policy#10]
Another policy should be, that users would be forced to change their passwords after

- a certain number of logins
- a certain number of days or months

cc @schiessle

**Comment by schiessle** [comment]
I remember that in I read a articles that such policies doesn't increase security, rather the opposite. Because usually people don't come up with good passwords every few weeks. So that passwords become weaker and weaker over time or they just rotate two simple passwords.

@LukasReschke what do you think?

**Comment by mar1u5** [comment]
This is a good point @schiessle :wink:

**Comment by tflidd** [comment]
Afterwards you can even change it back to the old password. Or you put an number in the end to iterate. I've never seen anybody who seriously changes difficult passwords.

**Comment by schiessle** [comment]
ok, so let's agree that this doesn't make a lot of sense.
